[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
test = "test"
remappings = [
    "@openzeppelin/contracts/=lib/CMTAT/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/CMTAT/openzeppelin-contracts-upgradeable/contracts/",
    "@fixdescriptorkit/contracts/=node_modules/@fixdescriptorkit/contracts/",
    "forge-std/=lib/forge-std/src/"
]
via_ir = true
optimizer = true
optimizer_runs = 200
